version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.1.4
    environment:
      TZ: "/usr/share/zoneinfo/Australia/Melbourne"
    steps:
      - checkout
      - run: sudo npm update -g
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:8.1.4
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run: npm test
  deploy:
    docker:
      - image: circleci/node:8.1.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ checksum "package.json" }}
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - "b5:8f:b1:bc:c7:2c:1c:cf:1f:32:70:5a:08:87:4f:8f"
      - run: ./deploy.sh

workflows:
  version: 2
  build_test_deploy:
      jobs:
        - build
        - test:
            requires:
              - build
        - deploy:
            requires:
              - test
            filters:
              branches:
                ignore: gh-pages
